import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { NeonAuthUIProvider, UserButton } from "@neondatabase/auth/react";
import { authClient } from "@/lib/auth/client";
import { cn } from "@/lib/utils";

const jetbrainsMono = JetBrains_Mono({
	subsets: ["latin"],
	variable: "--font-sans",
});

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			suppressHydrationWarning
			lang="en"
			className={cn(jetbrainsMono.variable, "dark")}
		>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<NeonAuthUIProvider
					authClient={authClient}
					redirectTo="/account/settings"
				>
					<header className="flex justify-end items-center p-4 gap-4 h-16">
						<UserButton size="icon" />
					</header>
					{children}
				</NeonAuthUIProvider>
			</body>
		</html>
	);
}
